---
- name: create prometheus user
  user:
    name: prometheus
    append: true
    shell: /usr/bin/nologin
    system: true
    create_home: false

- name: create prometheus dir
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: prometheus
    group: prometheus 
  loop:
    - /etc/prometheus
    - /var/lib/prometheus


- name: download prometheus 
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz" 
    dest: /tmp/
    mode: 0755 # chmod
    owner: prometheus
    group: prometheus
    
- name: Unarchive prometheus-2.22.0.linux-amd64.tar.gz
  unarchive:
    src: /tmp/prometheus-2.22.0.linux-amd64.tar.gz 
    dest: /tmp/ # /tmp/prometheus-2.22.0.linux-amd64
    remote_src: yes

- name: Copy prometheus and promtool binary
  copy:
    src: "{{ item }}" # for item in loop items, run this task
    dest: "/usr/local/bin/"
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes
  loop:
    - /tmp/prometheus-2.22.0.linux-amd64/prometheus
    - /tmp/prometheus-2.22.0.linux-amd64/promtool
    
  
- name: move the binary to the final destination
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/consoles"
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes
  loop: 
    - /tmp/prometheus-2.22.0.linux-amd64/consoles

- name: move the binary to the final destination
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/console_libraries"
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes
  loop: 
    - /tmp/prometheus-2.22.0.linux-amd64/console_libraries


- name: clean
  file:
    path: /tmp/prometheus-2.22.0.linux-amd64
    state: absent
    owner: prometheus
    group: prometheus


- name: install service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0755
  notify: restart_prometheus
    

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: prometheus configuration file
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: 
    - reload_prometheus
    - restart_prometheus