---
- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes
  notify: Send message to Admin

- name: reload_prometheus
  uri:
    url: http://54.208.99.112:9090/-/reload
    method: POST
    status_code: 200
    
- name: Send message to Admin
  debug:
    msg: "Prometheus restarted!"
